### ISSUE TITLE
helm push artifactory fails with file not exists

### ISSUE THREAD

**Issue by Gopishankarp** [belitre/helm-push-artifactory-plugin#18] opened 2020-02-04 15:17 UTC
Hi,
I have installed(extracted under **HELM_HOME/plugins** the latest version 'helm-push-artifactory-plugin-1.0.0'. in my windows 10 machine

When I try to push the helm package, getting the below error.

```
C:\Users\gponnusa>helm push-artifactory C:\Users\gpo\Downloads\clus-mgmt-1.0.0-626.tgz my-local
Error: exec: "C:\\Users\\gpo\\.helm\\plugins\\helm-push-artifactory-plugin-1.0.0/bin/helm-push-artifactory": file does not exist
```

I went through the closed issues, the same problem had been reported and resolved in build( v0.4.0)

Could you please help here

**Comment by belitre** [comment] 2020-02-05 13:17
Hi,

About the windows version.... looks like for some reason helm is looking for the executable in a path I didn't expect (maybe helm changed the way to find the plugin?), cause if you noticed, it's not checking for the executable in `HELM_HOME/plugins/helm-push-artifactory-plugin/bin` but in `HELM_HOME/plugins/helm-push-artifactory-plugin-1.0.0`. Can you tell me what version of helm are you using?

I'll take a looks as soon as I can to fix this, for now if you want I guess that just renaming the folder from `HELM_HOME/plugins/helm-push-artifactory-plugin` to `HELM_HOME/plugins/helm-push-artifactory-plugin-1.0.0` should work!

Cheers!

**Comment by Gopishankarp** [comment] 2020-02-05 14:24
Hi belitre,
Thanks for your reply.
It is currently extracted with name **helm-push-artifactory-plugin-1.0.0** under plugin folder. Still same error.

`Error: exec: "C:\\Users\\gpo\\.helm\\plugins\\helm-push-artifactory-plugin-1.0.0/bin/helm-push-artifactory": file does not exist`

Helm version:
**Client: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", **GitTreeState:"clean"}**

Thanks!

**Comment by belitre** [comment] 2020-02-05 15:38
Hi @Gopishankarp ,

Ok, if you are using helm 2.14.3, then you need to use the version [v0.4.0](https://github.com/belitre/helm-push-artifactory-plugin/releases/tag/v0.4.0)

Version 1.0.0 is only for helm 3.

Please give a try with version v0.4.0 and let me know if you have any problem. 

Cheers!

**Comment by Gopishankarp** [comment] 2020-02-07 03:48
Hi belitre,
I tried with the v0.4.0 version also. Even now I am facing the same problem.
`Error: exec: "C:\\Users\\gponnusa\\.helm\\plugins\\helm-push-artifactory-plugin-0.4.0/bin/helm-push-artifactory": file does not exist`

Any workaround to solve this.  I need to push the help package from my windows laptop to the remote helm repo.

**Comment by belitre** [comment] 2020-02-07 12:09
@Gopishankarp ok now I'm lost.... I tested just extracting the package in the plugins folder on my Windows 10 machine and it worked fine :S

I'll try to find some time this weekend to investigate this a bit more, sorry for the problems!

**Comment by belitre** [comment] 2020-02-08 23:20
Hi @Gopishankarp,

I just tested the plugin v0.4.0 with helm v2.14.3 in Windows 10 and it works.

What I did:
* Download helm v2.14.3 and extracted the zip to c:\helm
* Added C:\helm to my PATH environment variable
* Open a terminal, and run `helm init -c` to initialise helm
* Download the version v0.4.0 of the plugin to `%HOMEPATH%\.helm\plugins`
* Extracted the zip in the same folder (`%HOMEPATH%\.helm\plugins`), so the plugin is in the folder `%HOMEPATH%\.helm\plugins\helm-push-artifactory-plugin`, and the executable for the plugin is in `%HOMEPATH%\.helm\plugins\helm-push-artifactory-plugin\bin\helm-push-artifactory.exe`
* And just with that I can run `helm push-artifactory -h` and the plugin is there :)
![terminal](https://user-images.githubusercontent.com/3584328/74093419-74ff6d00-4ac9-11ea-9d17-314cde247601.PNG)

So, I recommend you to check everything is correctly configured for helm in your machine, maybe even delete the `%HOMEPATH%\.helm` folder and initialise helm again could help.

Closing the issue since it doesn't look the problem is in the plugin.

Cheers.

**Closed by belitre** 2020-02-08 23:20 UTC

**Comment by Gopishankarp** [comment] 2020-02-10 02:53
Hi Belitre,
Thanks a lot. But my still not resolved. %HOMEPATH%\.helm\plugins\helm-push-artifactory-plugin\**bin\helm-push-artifactory.exe** . There is no bin folder under **helm-push-artifactory-plugin**. Am i using the wrong package of the plugin. I could not find any other packge related to windows in the artifcatory. 
Could you please help me

**Comment by belitre** [comment] 2020-02-10 07:49
Hi @Gopishankarp,

Yeah, you are downloading the source code instead of the released binary :)

This is the correct link: [helm-push-artifactory-v0.4.0-windows-amd64.zip](https://github.com/belitre/helm-push-artifactory-plugin/releases/download/v0.4.0/helm-push-artifactory-v0.4.0-windows-amd64.zip)

You can find it if you click in `assets` in the v.0.4.0 release
<img width="939" alt="Screenshot 2020-02-10 at 07 47 19" src="https://user-images.githubusercontent.com/3584328/74130257-93ed2480-4bd9-11ea-88dd-4064e1cd757e.png">

Hope it will work!

Cheers.
